### ISSUE TITLE
'module' object has no attribute 'timezone'

### ISSUE THREAD

**Issue by rafiyah** [billtrust/postman-to-csv#1]
File "/usr/lib/python2.7/site-packages/postman_to_csv/postman_to_csv.py", line 112, in main
    run_date = datetime.datetime.utcnow().replace(microsecond = 0, tzinfo=**datetime.timezone**.utc).isoformat()
AttributeError: 'module' object has no attribute 'timezone'

**Should the bolded part in the message above be changed?**

**Comment by koslam** [comment]
I see you are running the code in Python 2.7. I don't believe that version has support for the datetime.timezone class. Please give it a shot using Python 3 and let me know if you are still seeing the error.

**Comment by koslam** [comment]
@rafiyah, just following up on this. Did running under Python 3 resolve the error for you?

**Comment by rafiyah** [comment]
Hey @koslam, thanks for taking a look at this issue! 
Apologies for not getting back to you sooner. I've tested this with an updated version of python and it's working perfectly for me :)
